# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI - Déployer l'application web

defaults:
  run:
    working-directory: FavViewerWeb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: FavViewerWeb/package-lock.json
        node-version: 22.x
        cache: 'npm'
    - run: npm i
    - run: npm run build -- --output-path=out/ --configuration=production
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        path: FavViewerWeb/out/browser
